/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"
	tarimv1 "trino-operator/apis/tarim/v1"
	versioned "trino-operator/pkg/apis/clientset/versioned"
	internalinterfaces "trino-operator/pkg/apis/informers/externalversions/internalinterfaces"
	v1 "trino-operator/pkg/apis/listers/tarim/v1"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TrinoInformer provides access to a shared informer and lister for
// Trinos.
type TrinoInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.TrinoLister
}

type trinoInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTrinoInformer constructs a new informer for Trino type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTrinoInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTrinoInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTrinoInformer constructs a new informer for Trino type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTrinoInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TarimV1().Trinos(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TarimV1().Trinos(namespace).Watch(context.TODO(), options)
			},
		},
		&tarimv1.Trino{},
		resyncPeriod,
		indexers,
	)
}

func (f *trinoInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTrinoInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *trinoInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&tarimv1.Trino{}, f.defaultInformer)
}

func (f *trinoInformer) Lister() v1.TrinoLister {
	return v1.NewTrinoLister(f.Informer().GetIndexer())
}
